version: "3.3"
services:
  grafana:
    image: grafana/grafana:7.2.1
    restart: on-failure
    environment:
      - TZ
    ports:
      - ${HOST:-127.0.0.1}:3000:3000
    volumes:
      - ${PWD}/infra/grafana/data/:/var/lib/grafana

  redis:
    image: redis:3.2
    hostname: redis
    ports:
      - ${HOST:-127.0.0.1}:6379:6379
    env_file:
      - ./.env
    restart: on-failure

  database:
    image: opennem/database:12
    restart: unless-stopped
    env_file: ./.env
    environment:
      - TZ
      - TIMESCALEDB_TELEMETRY=off
    ports:
      - ${HOST:-127.0.0.1}:15433:5432
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  grafana_data: {}
  postgis_data: {}
