version: "3.3"
services:
  redis:
    image: redis:7-alpine
    hostname: redis
    ports:
      - ${HOST:-127.0.0.1}:${REDIS_LOCAL_PORT:-6379}:6379
    env_file:
      - ./.env
    restart: on-failure

  postgres:
    image: timescale/timescaledb-ha:pg15-latest
    shm_size: "2GB"
    restart: unless-stopped
    env_file: ./.env
    environment:
      - TZ
      - TIMESCALEDB_TELEMETRY=off
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${HOST:-127.0.0.1}:${POSTGRES_LOCAL_PORT:-5432}:5432
    volumes:
      - db_data:/var/lib/postgresql/

  clickhouse:
    image: clickhouse/clickhouse-server
    restart: unless-stopped
    ports:
      - ${HOST:-127.0.0.1}:${CLICKHOUSE_LOCAL_PORT:-9000}:9000
      - ${HOST:-127.0.0.1}:${CLICKHOUSE_LOCAL_HTTP_PORT:-8123}:8123
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  db_data:
  clickhouse_data:
