version: "3.3"
services:
  grafana:
    image: grafana/grafana:7.2.1
    restart: on-failure
    environment:
      - TZ
    ports:
      - ${HOST:-127.0.0.1}:3000:3000
    volumes:
      - ${PWD}/infra/grafana/data/:/var/lib/grafana

  redis:
    image: redis:6-alpine
    hostname: redis
    ports:
      - ${HOST:-127.0.0.1}:6379:6379
    env_file:
      - ./.env
    restart: on-failure

  scrapyd:
    image: opennem/scrapyd
    restart: unless-stopped
    command: scrapyd --pidfile /tmp/scrapyd.pid
    volumes:
      - scrapyd_data:/app/dbs
      - scrapyd_logs:/app/logs
      - scrapyd_eggs:/app/eggs
    environment:
      - TZ
      - SCRAPYD=1
      - DATABASE_HOST_URL
      - REDIS_HOST_URL
      - GOOGLE_PLACES_API_KEY
      - ENV
      - SENTRY_URL
    ports:
      - ${HOST:-127.0.0.1}:6800:6800

  database:
    image: opennem/database:12.3
    restart: unless-stopped
    env_file: ./.env
    environment:
      - TZ
      - TIMESCALEDB_TELEMETRY=off
      - PGPASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${HOST:-127.0.0.1}:15433:5432
    volumes:
      - postgis_data:/var/lib/postgresql/data

  database_test:
    image: opennem/database
    restart: unless-stopped
    env_file: ./.env
    environment:
      - TZ
      - TIMESCALEDB_TELEMETRY=off
      - POSTGRES_USER=opennem_testing
    ports:
      - ${HOST:-127.0.0.1}:15440:5432

volumes:
  postgis_data: {}
  scrapyd_data:
    driver: local
  scrapyd_logs:
    driver: local
  scrapyd_eggs:
    driver: local
