version: "3.3"
services:
  grafana:
    image: grafana/grafana
    restart: on-failure
    environment:
      - TZ
    ports:
      - ${HOST:-127.0.0.1}:3000:3000

  redis:
    image: redis:3.2
    hostname: redis
    ports:
      - 6379:6379
    env_file:
      - ./.env
    restart: on-failure

  database:
    image: opennem/database:12
    restart: unless-stopped
    env_file: ./.env
    environment:
      - TZ
      - TIMESCALEDB_TELEMETRY=off
    ports:
      - ${HOST:-127.0.0.1}:15433:5432
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  db_data: {}
  pg_data: {}
  postgis_data: {}
  database_data: {}
