version: "3.3"
services:
  redis:
    image: redis:6-alpine
    hostname: redis
    ports:
      - ${HOST:-127.0.0.1}:6379:6379
    env_file:
      - ./.env
    restart: on-failure

  scrapyd:
    image: opennem/scrapyd
    restart: unless-stopped
    command: scrapyd --pidfile /tmp/scrapyd.pid
    volumes:
      - scrapyd_data:/app/dbs
      - scrapyd_eggs:/app/eggs
    environment:
      - TZ
      - SCRAPYD=1
      - DATABASE_HOST_URL
      - REDIS_HOST_URL
      - GOOGLE_PLACES_API_KEY
      - ENV
      - SENTRY_URL
    ports:
      - ${HOST:-127.0.0.1}:6800:6800

  postgres:
    image: opennem/database:dev
    restart: unless-stopped
    env_file: ./.env
    environment:
      - TZ
      - TIMESCALEDB_TELEMETRY=off
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MAX_CONNECTIONS=60
      - POSTGRES_SHARED_BUFFERS=64MB
    ports:
      - ${HOST:-127.0.0.1}:15433:5432
    volumes:
      - staging_data:/var/lib/postgresql

volumes:
  staging_data: {}
  scrapyd_data:
    driver: local
  scrapyd_eggs:
    driver: local
  mysql_data: {}
