version: "3.3"
services:
  redis:
    image: redis:6-alpine
    hostname: redis
    ports:
      - ${HOST:-127.0.0.1}:6379:6379
    env_file:
      - ./.env
    restart: on-failure

  scrapyd:
    image: opennem/scrapyd
    restart: unless-stopped
    command: scrapyd --pidfile /tmp/scrapyd.pid
    volumes:
      - scrapyd_data:/app/dbs
      - scrapyd_eggs:/app/eggs
    environment:
      - TZ
      - SCRAPYD=1
      - DATABASE_HOST_URL
      - REDIS_HOST_URL
      - GOOGLE_PLACES_API_KEY
      - ENV
      - SENTRY_URL
    ports:
      - ${HOST:-127.0.0.1}:6800:6800

  database:
    image: opennem/database:12.3
    restart: unless-stopped
    env_file: ./.env
    environment:
      - TZ
      - TIMESCALEDB_TELEMETRY=off
      - PGPASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${HOST:-127.0.0.1}:15433:5432
    volumes:
      - staging_data:/var/lib/postgresql/data

  mysql:
    image: mariadb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - TZ
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${HOST:-127.0.0.1}:15444:3306
    volumes:
      - mysql_data:/var/lib/mysql

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    restart: unless-stopped
    env_file: ./.env
    environment:
      - TZ
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${HOST:-127.0.0.1}:1433:1433
    # volumes:
    # - mssql_data:

volumes:
  staging_data: {}
  scrapyd_data:
    driver: local
  scrapyd_eggs:
    driver: local
  mysql_data: {}
