version: "3.3"
services:
  redis:
    image: redis:6-alpine
    hostname: redis
    ports:
      - ${HOST:-127.0.0.1}:6379:6379
    env_file:
      - ./.env
    restart: on-failure

  postgres:
    # image: opennem/database:dev
    image: timescale/timescaledb-postgis:latest-pg12
    shm_size: "2GB"
    restart: unless-stopped
    env_file: ./.env
    environment:
      - TZ
      - TIMESCALEDB_TELEMETRY=off
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${HOST:-127.0.0.1}:15433:5432
    volumes:
      - db_data:/var/lib/postgresql/

  proxy:
    image: wildcat/scylla
    ports:
      - ${HOST:-127.0.0.1}:8899:8899
      - ${HOST:-127.0.0.1}:8081:8081
    volumes:
      - proxy_data:/var/www/scylla

volumes:
  db_data: {}
  scrapyd_data:
    driver: local
  scrapyd_eggs:
    driver: local
  proxy_data: {}
