version: "3.3"
services:
  grafana:
    image: grafana/grafana
    restart: on-failure
    environment:
      - TZ
    ports:
      - ${HOST:-127.0.0.1}:3000:3000

  mysql:
    image: mariadb:10
    restart: always
    env_file: ./.env
    environment:
      - TZ
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    ports:
      - ${HOST:-127.0.0.1}:13306:3306
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:3.2
    hostname: redis
    ports:
      - 6379:6379
    env_file:
      - ./.env
    restart: on-failure

  postgres:
    image: postgres:12-alpine
    restart: always
    env_file: ./.env
    environment:
      - TZ
    ports:
      - ${HOST:-127.0.0.1}:15432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  database:
    image: kartoza/postgis
    restart: always
    env_file: ./.env
    environment:
      - TZ
      # - EXISTING_DATA_DIR=true
    ports:
      - ${HOST:-127.0.0.1}:15433:5432
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  db_data: {}
  pg_data: {}
  postgis_data: {}
