[tool.poetry]
name = "opennem-backend"
version = "3.10.0-alpha.13"
description = "OpenNEM Australian Energy Data Backend"
authors = ["Dylan McConnell <dylan.mcconnell@unimelb.edu.au>", "Nik Cubrilovic <nik@infotorch.org>"]
license = "MIT"
packages = [
    { include = "opennem" }
]

readme = "README.md"

homepage = "https://opennem.org.au"
repository = "https://github.com/opennem/opennem"

keywords = ["opennem", "analysis", "australia", "energy"]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.10",
  "Topic :: Scientific/Engineering"
]

include = [
  'README.md',
  'opennem/settings/logging.yml'
]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.23.0"
sentry-sdk = "^1.5.4"
pydantic = {extras = ["email"], version = "^1.8.2"}
alembic = "^1.6.2"
click = "^8.0.3"
huey = "^2.2.0"
redis = "3.4.1"
openpyxl = "^3.0.4"
geojson = "^2.5.0"
fastapi = "^0.78.0"
shapely = "^1.7.0"
pyyaml = "^5.3.1"
Wikidata = "^0.7.0"
wikipedia = "^1.4.0"
python-dateutil = "^2.8.1"
python-dotenv = "^0.20.0"
geojson-pydantic = "^0.4.2"
tomlkit = "^0.11.0"
validators = "^0.18.1"
python-magic = "^0.4.18"
cachetools = "^5.0.0"
psycopg2 = "^2.9.3"
xlrd = "^2.0.1"
datetime-truncate = "^1.1.1"
datedelta = "^1.3"
pandas = "^1.3.3"
osm2geojson = "^0.2.0"
Mako = "^1.1.4"
SQLAlchemy = "^1.4.15"
requests-cache = "^0.9.1"
py-trello = "^0.18.0"
gitignore-parser = "^0.0.8"
rich = "^12.2.0"
GeoAlchemy = "^0.7.2"
hypercorn = {extras = ["trio"], version = "^0.13.2"}
GeoAlchemy2 = "^0.12.1"
lxml = "^4.8.0"
aiohttp = {extras = ["speedups"], version = "^3.8.1"}
Pillow = "^9.1.1"
boto3 = "^1.23.7"
pyquery = "^1.4.3"


[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8 = "^4.0.1"
isort = "^5.8.0"
pylint = "^2.8.2"
rope = "^1.0.0"
pylint-sqlalchemy = "^0.2.0"
ipython = "^8.0.1"
pytest = "^7.0.1"
pytest-watch = "^4.2.0"
mypy = "^0.950"
mdutils = "^1.2.2"
sqlalchemy-stubs = "^0.4"
pycodestyle = "^2.8.0"
pytest-benchmark = {extras = ["histogram"], version = "^3.2.3"}
GitPython = "^3.1.12"
pdbpp = "^0.10.2"
pytest-sugar = "^0.9.4"
tox = "^3.23.1"
types-requests = "^2.25.2"
betamax = "^0.8.1"
types-python-dateutil = "^2.8.0"
types-pytz = "^2021.1.0"
coverage = "^6.3.1"
pytest-cov = "^3.0.0"
types-cachetools = "^5.0.0"
types-PyYAML = "^6.0.4"
aws-cdk-lib = "^2.9.0"
uvicorn = "^0.17.5"
pyflakes = "^2.4.0"

[tool.poetry.scripts]
opennem = 'opennem.cli:main'

[tool.poetry.extras]
postgres = ["psycopg2"]

[tool.black]
line-length = 120
target_version = ['py310']
include = '\.pyi?$'
exclude = '''
/(\.git/
  |\.eggs
  |__pycache__
  |\.cache
  |\.ipynb_checkpoints
  |\.mypy_cache
  |\.pytest_cache
  |\.tox
  |\.venv
  |node_modules
  |_build
  |buck-out
  |build
  |dist
  |media
  |infrastructure
  |templates
  |locale
)/
'''

[tool.mypy]
python_version = "3.10"
plugins = "sqlmypy,pydantic.mypy"
ignore_missing_imports = true
disallow_untyped_defs = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
