global:
  scrape_interval: 15s
  external_labels:
    monitor: "opennem-monitor"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "opennem_api"
    scrape_interval: 30s
    static_configs:
      - targets: ["0.0.0.0:8000"]
