name: Docker Image CI
on:
  push:
    branches:
      - master
  create:
    tags:
      - "*"
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sundays at 02:00

# permissions:
#   id-token: write
#   contents: read

jobs:
  buildimage:
    name: build docker images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - id: pre-step
        shell: bash
        run: echo "release-version=$(echo ${GITHUB_REF:10})" >> $GITHUB_OUTPUT

      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Build the Docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: opennem/opennem/opennem
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: infra/container/Dockerfile
          # tags: "latest,${{ steps.pre-step.outputs.release-version }}"
          tag_semver: true
          platforms: linux/amd64
          cache: ${{ github.event_name != 'schedule' }}

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-region: ap-southeast-2
      #     role-to-assume: arn:aws:iam::696911118106:role/github-action-ecr
      #     role-session-name: GithubActionBuild

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1
